[package]
name = "ted"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*"]

[dependencies]
ratatui = { workspace = true }
tui-textarea = { workspace = true }
ted_layout = { path = 'crates/ted_layout' }

[workspace.dependencies]
ratatui = "0.29.0"
tui-textarea = "0.7.0"
